/** @format */

const ALL_FETCHING = "layout/ALL_FETCHING";
const ALL_FETCH_SUCCESS = "layout/ALL_FETCH_SUCCESS";
const ALL_FETCH_FAILURE = "layout/ALL_FETCH_FAILURE";

const FETCHING = "layout/FETCHING";

const FETCH_SUCCESS = "layout/FETCH_SUCCESS";
const FETCH_FAILURE = "layout/FETCH_FAILURE";
const FETCHINGFEATURE = "layout/FETCHINGFEATURE";
const FETCH_SUCCESSFEATURE = "layout/FETCH_SUCCESSFEATURE";
const FETCH_FAILUREFEATURE = "layout/FETCH_FAILUREFEATURE";
const MORE_FETCHING = "layout/MORE_FETCHING";
const MORE_FETCH_SUCCESS = "layout/MORE_FETCH_SUCCESS";
const MORE_FETCH_FAILURE = "layout/MORE_FETCH_FAILURE";

const SWITCH_MODE = "layout/SWITCH_MODE";

export {
  ALL_FETCHING,
  ALL_FETCH_SUCCESS,
  ALL_FETCH_FAILURE,
  FETCHING,
  FETCH_SUCCESS,
  FETCH_FAILURE,
  MORE_FETCHING,
  MORE_FETCH_SUCCESS,
  MORE_FETCH_FAILURE,
  SWITCH_MODE,
  FETCHINGFEATURE,
  FETCH_SUCCESSFEATURE,
  FETCH_FAILUREFEATURE
};
