/**
 * created by Inspire UI @author(dang@inspireui.com)
 * @format
 */

const PAYMENT_SETTING_FETCHING = "payment/SETTING_FETCHING";
const PAYMENT_SETTING_SUCCESS = "payment/SETTING_SUCCESS";
const PAYMENT_SETTING_FAILURE = "payment/SETTING_FAILURE";

const PAYMENT_ADD_CREDIT_CARD_FETCHING = "payment/ADD_CREDIT_CARD_FETCHING";
const PAYMENT_ADD_CREDIT_CARD_SUCCESS = "payment/ADD_CREDIT_CARD_SUCCESS";
const PAYMENT_ADD_CREDIT_CARD_FAILURE = "payment/ADD_CREDIT_CARD_FAILURE";

const PAYMENT_COMPLETE_CREDIT_CARD_FETCHING =
  "payment/COMPLETE_CREDIT_CARD_FETCHING";
const PAYMENT_COMPLETE_CREDIT_CARD_SUCCESS =
  "payment/COMPLETE_CREDIT_CARD_SUCCESS";
const PAYMENT_COMPLETE_CREDIT_CARD_FAILURE =
  "payment/COMPLETE_CREDIT_CARD_FAILURE";

const PAYMENT_COMPLETE_FREE_FETCHING = "payment/COMPLETE_FREE_FETCHING";
const PAYMENT_COMPLETE_FREE_SUCCESS = "payment/COMPLETE_FREE_SUCCESS";
const PAYMENT_COMPLETE_FREE_FAILURE = "payment/COMPLETE_FREE_FAILURE";

export {
  PAYMENT_SETTING_FETCHING,
  PAYMENT_SETTING_SUCCESS,
  PAYMENT_SETTING_FAILURE,
  PAYMENT_ADD_CREDIT_CARD_FETCHING,
  PAYMENT_ADD_CREDIT_CARD_SUCCESS,
  PAYMENT_ADD_CREDIT_CARD_FAILURE,
  PAYMENT_COMPLETE_CREDIT_CARD_FETCHING,
  PAYMENT_COMPLETE_CREDIT_CARD_SUCCESS,
  PAYMENT_COMPLETE_CREDIT_CARD_FAILURE,
  PAYMENT_COMPLETE_FREE_FETCHING,
  PAYMENT_COMPLETE_FREE_SUCCESS,
  PAYMENT_COMPLETE_FREE_FAILURE,
};
