/** @format */

const ALL_FETCHING = "products/ALL_FETCHING";
const ALL_FETCH_SUCCESS = "products/ALL_FETCH_SUCCESS";
const ALL_FETCH_FAILURE = "products/ALL_FETCH_FAILURE";

const MORE_ALL_FETCHING = "products/MORE_ALL_FETCHING";
const MORE_ALL_FETCH_SUCCESS = "products/MORE_ALL_FETCH_SUCCESS";
const MORE_ALL_FETCH_FAILURE = "products/MORE_ALL_FETCH_FAILURE";

const FETCHING = "products/FETCHING";
const FETCH_SUCCESS = "products/FETCH_SUCCESS";
const FETCH_FAILURE = "products/FETCH_FAILURE";

const MORE_FETCHING = "products/MORE_FETCHING";
const MORE_FETCH_SUCCESS = "products/MORE_FETCH_SUCCESS";
const MORE_FETCH_FAILURE = "products/MORE_FETCH_FAILURE";

const CLEAN_PRODUCT = "products/CLEAN";

export {
  ALL_FETCHING,
  ALL_FETCH_SUCCESS,
  ALL_FETCH_FAILURE,
  MORE_ALL_FETCHING,
  MORE_ALL_FETCH_SUCCESS,
  MORE_ALL_FETCH_FAILURE,
  FETCHING,
  FETCH_SUCCESS,
  FETCH_FAILURE,
  MORE_FETCHING,
  MORE_FETCH_SUCCESS,
  MORE_FETCH_FAILURE,
  CLEAN_PRODUCT,
};
